### PR TITLE
fix: stabilize hashCode() for Enums using proto ordinals

### LINKED ISSUE #227: Generated hashCode() for OneOf classes must not depend on Enum.hashCode()
All PBJ objects have auto-generated `hashCode()` implementation. For `OneOf` fields, hash codes are calculated like this:

```java
        return (31 + kind.hashCode()) * 31 + (value == null ? 0 : value.hashCode());
```

`kind` above is a enum, so its hash code is actually `Enum.hashCode()`. Here is the problem: this method is not deterministic, it returns different values across process runs:

```java
        int hc = hash;
        if (hc == 0) {
            hc = hash = System.identityHashCode(this);
        }
        return hc;
```

Since we use hash codes in long-term storage, they must be the same across node runs. It means `Enum.hashCode()` must not be used anywhere in our code. There may be other usages than in `OneOf`.

One quick option is to use `kind.ordinal()` (or some derivative) instead of `kind.hashCode()`, but there may be better solutions.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
Modifying the original implementation at https://github.com/hashgraph/pbj/pull/228 by switching from using `Enum.name().hashCode()` to `Integer.hashCode(EnumWithProtoMetadata.protoOrdinal())`.

**Related issue(s)**:

Fixes #227 

**Notes for reviewer**:
* All tests in all three PBJ sub-projects pass.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java [hunk 1]
```diff
@@ -22,6 +22,7 @@ public record ComparableOneOf<E extends Enum<E>>(E kind, Comparable value) imple
         if (kind == null) {
             throw new NullPointerException("An enum 'kind' must be supplied");
         }
+        assert kind instanceof EnumWithProtoMetadata : "OneOf 'kind' must implement EnumWithProtoMetadata";
```
Comment (netopyr) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java:25]: Is an `assert` the right approach? Why not a regular check?

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java [hunk 2]
```diff
@@ -44,8 +45,8 @@ public boolean equals(Object o) {
 
     @Override
     public int hashCode() {
-        // name().hashCode() and NOT Enum.hashCode() because the latter changes between runs
-        return (31 + kind.name().hashCode()) * 31 + (value == null ? 0 : value.hashCode());
+        return (31 + Integer.hashCode(((EnumWithProtoMetadata)kind).protoOrdinal())) * 31
```
Comment (netopyr) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java:48]: Nit: I don't think adding 31 provides a lot of value. It basically just adds a constant to the result. But it does not hurt.

File: pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java [hunk 3]
```diff
@@ -46,9 +48,19 @@ void equalsWorks() {
...
 
-    public enum TestEnum {
+    public enum TestEnum implements EnumWithProtoMetadata {
         KIND1,
-        KIND2
+        KIND2;
+
+        @Override
+        public int protoOrdinal() {
+            return ordinal();
```
Comment (netopyr) [inline pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java:57]: The implementation of `protoOrdinal()` should be more complex IMO, resulting in negative values and gaps.

File: pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java [hunk 4]
```diff
@@ -28,7 +29,8 @@ void asReturnsValue() {
     @Test
     void hashCodeReturnsHashCode() {
```
Comment (netopyr) [inline pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java:30]: I suggest to implement this as a parameterized tests that checks all values of `TestEnum`.

**Review by netopyr — APPROVED** [review]
LGTM

Just some minor comments that can be fixed later.

**Review by jsync-swirlds — APPROVED** [review]

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java:25]: Yes, it should suffice. The `hashCode()` implementation will error out with a class cast exception if this assertion is not satisfied. So as far as the correctness is concerned, the current implementation is solid.

Using an `assert` here helps improve the performance a little bit because we really don't expect to see anything but `EnumWithProtoMetadata` here. But like mentioned above, even if that happens, we'll error out later on then.

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java (hunk 2 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ComparableOneOf.java:48]: The `31` comes from an implementation of `Objects.hashCode([])` which we removed nad replaced with this code because it created a new array and hurt the performance. However, we wanted to keep the hash codes values intact, hence the `31`.

File: pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java (hunk 3 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java:57]: This is a test implementation and we currently don't have any tests that would benefit from a more complex implementation here.

File: pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java (hunk 4 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-runtime/src/test/java/tests/ComparableOneOfTest.java:30]: Good idea. I filed https://github.com/hashgraph/pbj/issues/232 to implement this at a later time.
