### PR TITLE
fix: handle partially-qualified inner message names

### LINKED ISSUE #414: Allow referencing inner messages
A sample .proto model in the parent ticket uses references to inner messages. PBJ is currently unable to compile this model unless all the references use fully-qualified names.

The ask is to allow using non-fully-qualified names when referencing inner messages.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
Re-implementing fully qualified names look-up that now allows one to use partially qualified names to refer to inner and/or imported messages. This is the first part of a bigger issue described at https://github.com/hashgraph/pbj/issues/263.

**Related issue(s)**:

Fixes #414

**Notes for reviewer**:
A new test is added to verify the new behavior.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jsync-swirlds — APPROVED** [review]
LGTM.

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java [hunk 1]
```diff
@@ -132,6 +132,48 @@ public String getUnqualifiedProtoName(final ParserRuleContext context) {
         }
     }
 
+    private String getFullyQualifiedProtoMessageName(
+            final String messageType, final File protoSrcFile, final ParserRuleContext context) {
```
Comment (artemananiev) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:136]: protoSrcFile seems redundant...

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java [hunk 2]
```diff
@@ -132,6 +132,48 @@ public String getUnqualifiedProtoName(final ParserRuleContext context) {
...
+        ParserRuleContext parentContext = context;
+        while ((parentContext = parentContext.getParent()) != null) {
+            if (parentContext instanceof MessageDefContext ctx) {
+                final String msgName = ctx.messageName().getText();
+                final String tryName =
+                        getFullyQualifiedProtoMessageName(msgName + "." + messageType, protoSrcFile, ctx);
+                if (tryName != null) {
+                    return tryName;
+                }
+            } else if (parentContext instanceof Protobuf3Parser.ProtoContext ctx) {
```
Comment (artemananiev) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:159]: Can parentContext be anything else besides MessageDefContext or Protobuf3Parser.ProtoContext?

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java [hunk 3]
```diff
@@ -132,6 +132,48 @@ public String getUnqualifiedProtoName(final ParserRuleContext context) {
...
+                // We've reached the top-level context. Weirdly, the grammar allows for multiple package
+                // statements, so simply try each:
+                for (final Protobuf3Parser.PackageStatementContext psc : ctx.packageStatement()) {
+                    final String packageName = psc.fullIdent().getText();
+                    final String prefix = (packageName == null || packageName.isBlank()) ? "" : (packageName + ".");
+                    final String tryName = getFullyQualifiedProtoMessageName(prefix + messageType, protoSrcFile, ctx);
```
Comment (artemananiev) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:165]: I wonder if it makes sense to call this method recursively, if packageName is null/blank

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:136]: Good catch. Removing it.

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java (hunk 2 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:159]: Yes. I used a debugger to see the whole tree, and there's a lot of different contexts, like "one-of body", "message body", and half a dozens of others. However, as far as resolving names is concerned, only the `MessageDefContext` and `ProtoContext` seem to matter, at least in the sample .proto models that this fix is trying to support. So for now we simply skip all the others and keep walking upwards as they're irrelevant.

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java (hunk 3 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:165]: Probably not. Tests still seem to pass if I `continue` on a blank package name, so I'll skip that.

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java (hunk 2 above)
Comment (jsync-swirlds) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:157]: If enum has its own context, we might want to handle that here as well.

**Review by jsync-swirlds — APPROVED** [review]

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java (hunk 2 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/LookupHelper.java:157]: It may be unusual to define inner types inside an enum, at least in protobuf. Also, our grammar doesn't support this currently:

https://github.com/hashgraph/pbj/blob/d29a03004c897f96dcd84b1a580941e11bd465f1/pbj-core/pbj-compiler/src/main/antlr/com/hedera/hashgraph/protoparser/grammar/Protobuf3.g4#L159-L187

We can consider supporting this if/when we have a real use case for that, and after we confirm protobuf is supposed to support that. For now, I think we're already covering 99.(9)% of real-world use-cases.
