### PR TITLE
Try faster hashCode

### LINKED ISSUE #424: Bytes.hashCode() performance
### Description

Bytes.hashCode shows up as the biggest number of loop iterations in code base.
Image

### Steps to reproduce

measure performance of Bytes.hashCode()

### Additional context

_No response_

### Hedera network

_No response_

### Version

v0.9.20

### Operating system

None

### PR DESCRIPTION
**Pull request by jasperpotts**
@anthony-swirldslabs : A second revision of the fix on 3/31/2025. This time we always use our own hash code computation code and never rely on JDK directly. Also, the benchmark has been modified to actually test the `hashCode` method specifically. Results for small (16), medium (16K), and large (16M) Bytes objects:

**Before the fix:**
```
Benchmark                            Mode  Cnt          Score          Error  Units
BytesHashCodeBench.hashLargeBytes   thrpt    5         62.785 ±        2.616  ops/s
BytesHashCodeBench.hashMediumBytes  thrpt    5      64916.981 ±     1178.676  ops/s
  BytesHashCodeBench.hashSmallBytes   thrpt    5  156480715.770 ± 10117792.960  ops/s
```

**With the fix:**
```
Benchmark                            Mode  Cnt            Score           Error  Units
BytesHashCodeBench.hashLargeBytes   thrpt    5  17794927753.539 ± 120647815.286  ops/s
BytesHashCodeBench.hashMediumBytes  thrpt    5  17793757339.364 ± 137804766.981  ops/s
BytesHashCodeBench.hashSmallBytes   thrpt    5  17711207197.438 ± 541245113.180  ops/s
```

A 100x improvement even for a small Bytes of size 16. A much larger improvement for larger Bytes objects.

-------------------------
Below is the description from the original revision of the fix from @jasperpotts :
-------------------------

Aims to fix #424 , bellow are results on mac laptop.

hashCodeResults

### CODE REVIEW

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java [hunk 1]
```diff
@@ -466,11 +471,20 @@ public boolean equals(@Nullable final Object o) {
...
     @Override
     public int hashCode() {
-        int h = 1;
-        for (int i = start + length - 1; i >= start; i--) {
-            h = 31 * h + UnsafeUtils.getArrayByteNoChecks(buffer, i);
+        if (hashCode == 0 && length > 0) {
+            if (length == 1) {
+                hashCode = 31 + (int) buffer[start];
+            } else if (start == 0 && length == buffer.length) {
+                hashCode = Arrays.hashCode(buffer);
```
Comment (anthony-swirldslabs) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java:478]: I'm concerned about using JDK-provided methods for hashing. We've already encountered a case where the Java hash code could be stored in state. That code obviously breaks whenever the JDK changes its internal implementation. Further, some implementations may even return a different hash code value between JVM runs.

Could you please benchmark the cached version using the original loop only and see if the results are dramatically worse than using the `Arrays.hashCode`?

Comment (artemananiev) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/io/buffer/Bytes.java:478]: I second to that. Using `Arrays.hashCode()` was discussed in https://github.com/hashgraph/pbj/issues/389, and a decision was made to not use it, basically for the reasons outlined above by Anthony. Backwards compatibility with current implementation can be solved (e.g. switching to this new PBJ version in mega map with full data migration). However, the concern about future Java versions cannot be addressed

**Review by imalygin — DISMISSED** [review]

**Review by imalygin — APPROVED** [review]

**Review by alex-kuzmin-hg — APPROVED** [review]
LGTM. I'll perf-test after merge

**Review by OlegMazurov — APPROVED** [review]
