### PR TITLE
Fixed all compiler and doc warnings

### LINKED ISSUE #345: Fix warnings during build
### Description

There are too many warnings printed during the build these should be fixed.

### Steps to reproduce

Run build and look at all the pretty RED text!

### Additional context

_No response_

### Hedera network

_No response_

### Version

v0.9.14

### Operating system

None

### PR DESCRIPTION
**Pull request by jasperpotts**
I had enough of all the warnings, this cleans them all up, YAY :-) Fixes #345

### CODE REVIEW

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java [hunk 1]
```diff
@@ -55,6 +56,42 @@ public final class ModelGenerator implements Generator {
 		hashCode += hashCode << 30;
 		""".indent(DEFAULT_INDENT);
 
+	public static void main(String[] args) {
+		String test = """
```
Comment (anthony-swirldslabs) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java:60]: Minor: I think this `main()` belongs to tests, not production code.

**Review by anthony-swirldslabs — COMMENTED** [review]
Looks good overall, just one minor comment.
However, it seems that PR checks, including unit tests, fail. Please take a look.

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java (hunk 1 above)
Comment (jasperpotts) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java]: Opps I left it in by accident, removed. Also found couple failing tests and a bug in enum handling of depricated values I also fixed.

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/EnumGenerator.java [hunk 2]
```diff
@@ -57,7 +57,18 @@ public static void generateEnumFile(Protobuf3Parser.EnumDefContext enumDef, File
 								.replaceAll("/n\s*/n","/n") //  remove empty lines
 				);
 				maxIndex = Math.max(maxIndex, enumNumber);
-				enumValues.put(enumNumber, new EnumValue(enumValueName, false,enumValueJavaDoc));
+				// extract if the enum is marks as deprecated
+				boolean deprecatedEnumValue = false;
+				if(item.enumField().enumValueOptions() != null && item.enumField().enumValueOptions().enumValueOption() != null) {
+					for(var option:item.enumField().enumValueOptions().enumValueOption()) {
```
Comment (anthony-swirldslabs) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/EnumGenerator.java:63]: Minor: space after `if`, and after `for`.

**Review by anthony-swirldslabs — APPROVED** [review]

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/EnumGenerator.java (hunk 2 above)
Comment (jasperpotts) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/EnumGenerator.java:63]: Will skip this for now, in talks with Joseph on getting spotless enabled for PBJ. Can fix then
