### PR TITLE
fix 68: introduce SingleFuzzTest

### LINKED ISSUE #68: Add Tests for Malformed Data
### Problem

PBJ has not been fully tested for parsing streams of badly formed data. 

### Solution

Write unit tests and file issues as needed to fix any cases where input data could cause problems. As long as all badly formed data can not cause high resource usage like CPU or Memory and it throws a ParseException if anything goes wrong then we are all good.

Examples of badly formed data could be:

- Very deep nested messages
- Large Lists
- Large lengths for size of length encoded data
- Probably Others

Also adding fuzz testing could be a good idea to make really sure.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
Introducing the `SingleFuzzTest` class to support fuzz testing.

This is the first in a series of pull requests that will ultimately build a framework to run fuzz testing for pbj.

Here I'm introducing a new utility class that can perform a single randomized run of a fuzz test and return a result value that indicates whether the test was successful or more testing may be needed. See javadocs for more details.

Please note that building the entire fuzz testing framework is outside of scope of this particular PR and will be done in future, separate PRs.

**Related issue(s)**:

Fixes #68 

**Notes for reviewer**:
```
pbj-integration-tests]$ ./gradlew test --info
...
STANDARD_OUT
    SingleFuzzTest 0: Object: AccountID[shardNum=3, realmNum=2, account=OneOf[kind=ACCOUNT_NUM, value=1]]
    SingleFuzzTest 0: Bytes: ByteArrayBufferedData[8,3,16,2,24,1]
    SingleFuzzTest 0: Fuzz bytes: ByteArrayBufferedData[8,3,16,2,223,1]
    SingleFuzzTest 0: Fuzz exception: Cannot understand wire_type of 7
    A fuzz test for AccountID[shardNum=3, realmNum=2, account=OneOf[kind=ACCOUNT_NUM, value=1]] resulted in DESERIALIZATION_FAILED
...
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+ * or the framework runs out of the maximum number of attempts, or a timeout
+ * occurs.
+ * <p>
+ * This class is thread-safe and can be called concurrently from multiple threads
+ * as long as the input parameters are immutable or thread-safe.
+ */
+public final class SingleFuzzTest {
+    private final static AtomicInteger TEST_ID_GENERATOR = new AtomicInteger(0);
+
+    private static <T> BufferedData write(final T object, final Codec<T> codec, final int size) throws Exception {
```
Comment (artemananiev) [inline pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java:29]: As far as I remember, `Codec` has a method to measure size of object, in bytes. So `size` here is probably redundant.

File: pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+        AccountID accountID = AccountID.newBuilder().accountNum(1).realmNum(2).shardNum(3).build();
+        SingleFuzzTestResult singleFuzzTestResult = SingleFuzzTest.fuzzTest(
+                accountID,
+                AccountID.PROTOBUF,
+                new Random()
+        );
+        System.out.println("A fuzz test for " + accountID + " resulted in " + singleFuzzTestResult);
+
+        // It's a no-op by design currently. See javadoc for details.
+        assertNotNull(singleFuzzTestResult);
```
[the remark this answers is not in the document]
Comment (anthony-swirldslabs) [reply pbj-integration-tests/src/test/java/com/hedera/pbj/intergration/test/SampleFuzzTest.java:32]: That's correct. However, Codacy insists that a test must have a call to assert*() and/or fail(), so I had to add this no-op assertion in the second commit (hence the comment right above it.)

File: pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply pbj-integration-tests/src/main/java/com/hedera/pbj/integration/fuzz/SingleFuzzTest.java:29]: You're correct. However, the code calling this method has already called codec.measureRecord() at lines 53 and 84 below. The implementation of the measureRecord() is such that it iterates over all the fields of an object, which may be rather expensive for large objects. Since I'll need to run this test many times in order to gather statistics (because a single fuzz test run may not reveal issues), I figured I'd optimize it a bit here and not call measureRecord() the second time since I already have the value. Please let me know what you think.

**Review by artemananiev — APPROVED** [review]
