### PR TITLE
fix: 220: Re-implement null checks for Bytes and Strings

### LINKED ISSUE #220: Re-implement null checks for Bytes and Strings
`null` was disallowed for Bytes and String at https://github.com/hashgraph/pbj/pull/214

However, services code seems to assign `null` Bytes left and right, e.g.:

https://github.com/hashgraph/hedera-services/blob/c92de0026ec8079d45e480b0eb3b450fbd06f198/hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/AliasUtils.java#L75-L85

And then the `null` return value fails in a PBJ model validator.

We need to re-implement that fix and instead inject a full-fledged constructor into models that would substitute `null` with default values for Bytes and Strings.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
Re-implementing the original fix for https://github.com/hashgraph/pbj/issues/211 by allowing null values for Bytes and Strings as inputs to model constructor/Builder, and automatically substituting the nulls with default values (Bytes.EMPTY or "").

This is necessary because code in hedera-services constructs objects and passes null values for such fields in a few places, so we have to support the null values as inputs. However, the fix makes sure that internally, we don't allow null values for private fields of these types in the model records.

Note that the Builder constructor does allow null OneOf fields as inputs. This is by design. This prevents any potential failures if anyone passes such nulls today because they were always allowed. This also implies that the code would use convenience methods exposed by the Builder for various OneOf variations. And finally, during a call to `build()`, an uninitialized OneOf field will still be caught by the model constructor. So it's fine to allow null as input for OneOf fields in the Builder constructor.

**Related issue(s)**:

Fixes #220 

**Notes for reviewer**:
* All tests pass in PBJ.
* Also, new unit tests are added.
* Also, hedera-services unit tests pass.
* Finally, while 4 HAPI tests from `gr hapiTestToken -Dfile.encoding=UTF-8 --scan` still fail, they fail with errors unrelated to this fix, and they fail all the same when running with PBJ w/o this fix. So as far as the original regression related to the 'null' values handling is concerned, it is now fixed with this PR, and the current failures are completely unrelated to this PBJ behavior.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java [hunk 1]
```diff
@@ -363,6 +361,58 @@ public int hashCode() {
...
+							);
+							break;
+						}
+						default:
+							sb.append("this.$name = $name;".replace("$name", field.nameCamelFirstLower()));
+							break;
+					}
+					return sb.toString();
+				}).collect(Collectors.joining("\n")).indent(DEFAULT_INDENT * 2))
+				;//.indent(DEFAULT_INDENT);
```
Comment (imalygin) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java:413]: please, clean it up.

**Review by imalygin — APPROVED** [review]

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/ModelGenerator.java:413]: Good catch. I'll do this a follow-up PR when I'm re-applying the `maxDepth` fix later today.
