### PR TITLE
fix: 208: limit max size

### LINKED ISSUE #208: Limit max Bytes size
Introduce a max size for a Bytes object to be parsed from binary form. Ideally, we want to configure this value in the model definition, but that can be implemented as a feature at a later time.

For now, we want to hard-code a maximum supported number in the parser and fail the parsing if we encounter a larger Bytes object in an input stream.

@jasperpotts to provide the number.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
This fix introduces a default limit of 21K on repeated/length-encoded field sizes. When the parser encounters a field with a greater size, it errors out with ParseException.

This is a quick solution for release 48.

In a future release, we'll extend the functionality as described at https://github.com/hashgraph/pbj/issues/209.

**Related issue(s)**:

Fixes #208 

**Notes for reviewer**:
All unit tests and all integration tests, including the fuzzTest, pass in all three PBJ sub-projects.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by imalygin — APPROVED** [review]

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java [hunk 1]
```diff
@@ -200,7 +200,27 @@ public static double readDouble(final ReadableSequentialData input) {
      * @return Read string
      */
     public static String readString(final ReadableSequentialData input) throws IOException {
+        try {
+            return readString(input, Long.MAX_VALUE);
```
Comment (jasperpotts) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java:204]: Don't love the calling here with Long.MAX_VALUE to do the equivalent of disabling check as we still pay performance cost.

**Review by jasperpotts — APPROVED** [review]

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoParserTools.java:204]: Yes, I was thinking the same when making this change. I decided to go with reusing the code instead of making a copy for a simple reason: in an ideal world, nobody should be calling this particular method outside of PBJ, and PBJ Codecs now only call the maxSize-version of this method now.

So as far as parsing with PBJ codecs is concerned, the performance should be top-notch. And those unlucky who decided to call ProtoParserTools methods directly from elsewhere should reconsider their choices. :)
