### PR TITLE
Fix: exposed multiple methods of ProtoParserTools and added unit test…

### LINKED ISSUE #74: Some sizeOf methods aren't exposed publicly from ProtoWriterTools
Several `sizeOfXYZ()` methods are not public in `ProtoWriterTools`. For example:

* sizeOfTag()
* sizeOfVarInt32()
* sizeOfUnsignedVarInt32()
* etc.

I don't know why other methods are public, but these aren't. My guess is these methods are too low level and aren't expected to be used by 3rd-party code. For example, to get size of an integer, they should always use `sizeOfInteger()`, which internally calls these private methods.

However, in MerkleDb PBJ code I do need at least `sizeOfTag()`, since MerkleDb writes and reads field tags manually, not using codecs. Also, `sizeOfInteger()` has valid optimization of skipping default int values (i.e. zero), but in case of MerkleDb it's sometimes helpful to write default values, too, to make file structure a little bit more regular (still protobuf compatible).

### PR DESCRIPTION
**Pull request by imalygin**
Exposed multiple methods of ProtoParserTools and added unit tests for them. Also, added `readNextFieldNumber` method

**Related issue(s)**:

Fixes #74 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java [hunk 1]
```diff
@@ -805,7 +825,7 @@ private static int sizeOfUnsignedVarInt32(final int value) {
      * @param value The int value to get encoded size for
      * @return the number of bytes for encoded value
      */
-    private static int sizeOfUnsignedVarInt64(long value) {
+    public static int sizeOfUnsignedVarInt64(long value) {
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java:828]: Do these two methods need to be public, given that `sizeOfVarIn32/64()` is now available?

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java [hunk 2]
```diff
@@ -1250,14 +1270,9 @@ public static int sizeOfEnumList(FieldDefinition field, List<? extends EnumWithP
...
-        if (!field.oneOf() && list.isEmpty()) {
-            return 0;
-        }
         int size = 0;
-
         for (final String value : list) {
-            size += sizeOfTag(field, ProtoConstants.WIRE_TYPE_DELIMITED);
+            size += sizeOfTag(field, WIRE_TYPE_DELIMITED);
             final int strSize = sizeOfStringNoTag(field, value);
             size += sizeOfVarInt32(strSize) + strSize;
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java:1277]: Can be rewritten as
```java
size += sizeOfDelimited(field, sizeOfStringNoTag(field, value));
```

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java [hunk 3]
```diff
@@ -1052,7 +1072,7 @@ public static int sizeOfString(FieldDefinition field, String value) {
             return 0;
         }
         final int size = sizeOfStringNoTag(field, value);
-        return sizeOfTag(field, ProtoConstants.WIRE_TYPE_DELIMITED) + sizeOfVarInt32(size) + size;
+        return sizeOfTag(field, WIRE_TYPE_DELIMITED) + sizeOfVarInt32(size) + size;
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java:1075]: Use `sizeOfDelimited()` here?

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java [hunk 4]
```diff
@@ -1052,7 +1072,7 @@ public static int sizeOfString(FieldDefinition field, String value) {
             return 0;
         }
         final int size = sizeOfStringNoTag(field, value);
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java:1074]: I wonder if `field` is actually needed in `sizeOfStringNoTag()` It's only used to check for oneOf() in case of empty strings, but for empty strings the size is zero anyway...

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java [hunk 5]
```diff
@@ -1293,14 +1304,14 @@ public static <T> int sizeOfMessageList(FieldDefinition field, List<T> list, ToI
...
-        }
         int size = 0;
         for (final RandomAccessData value : list) {
-            size += Math.toIntExact(sizeOfTag(field, ProtoConstants.WIRE_TYPE_DELIMITED) + sizeOfVarInt32(Math.toIntExact(value.length())) + value.length());
+            size += Math.toIntExact(sizeOfTag(field, WIRE_TYPE_DELIMITED) + sizeOfVarInt32(Math.toIntExact(value.length())) + value.length());
         }
         return size;
     }
+
+    public static int sizeOfDelimited(final FieldDefinition field, final int length) {
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java:1314]: 👍

File: pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java [hunk 6]
```diff
@@ -0,0 +1,759 @@
...
+    }
+
+    @Test
+    void testWriteOptionalFloat() {
+        FieldDefinition definition = createOptionalFieldDefinition(FLOAT);
+        final float valToWrite = randomLargeInt();
+        writeOptionalFloat(bufferedData, definition, valToWrite);
+        bufferedData.flip();
+        assertTypeDelimitedTag(definition);
+        assertEquals(MAX_VAR_FLOAT_SIZE, bufferedData.readVarInt(false));
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java:382]: `MAX_VAR_FLOAT_SIZE` name is confusing. Floats are not variable, they are fixed 4 bytes. Optional floats are either 0 bytes (null value), or sizeOfDelimited(field, 4) bytes. `OPTIONAL_FLOAT_SIZE` would be a better name, in my opinion. Also, check my comment to `MAX_VAR_FLOAT_SIZE`.

File: pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java [hunk 7]
```diff
@@ -0,0 +1,759 @@
...
+import java.util.Collections;
+import java.util.List;
+import java.util.random.RandomGenerator;
+
+class ProtoWriterToolsTest {
+
+    public static final int SIZE_OF_TAG = 1;
+    public static final int SIZE_OF_LENGTH_VAR = 1;
+    public static final int MAX_VAR_INT_SIZE = 6;
+    public static final int MAX_VAR_FLOAT_SIZE = 5;
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java:81]: What does this mean, exactly?

My math is: max value here is when field ID is max (like 2^29 - 1), in this case total size of non-null optional float will be 5 (delimited tag) + 5 (delimited length) + 4 (fixed float)

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java (hunk 1 above)
Comment (imalygin) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java]: You're right, they don't need to be. Fixed

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java (hunk 2 above)
Comment (imalygin) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java]: Done.

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java [hunk 8]
```diff
@@ -20,6 +20,9 @@ public class Utf8Tools {
      *     surrogates)
      */
     static int encodedLength(CharSequence sequence) throws IOException {
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java:22]: final

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java [hunk 9]
```diff
@@ -20,6 +20,9 @@ public class Utf8Tools {
...
+        if(sequence == null) {
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java:23]: Add a whitespace between `if` and `(`

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java (hunk 4 above)
Comment (imalygin) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/ProtoWriterTools.java]: Yes, it can be removed. I covered the case of null oneOf() case (that required a check for null in `Utf8Tools#encodedLength`, after that the field could be safely removed.

File: pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java [hunk 10]
```diff
@@ -46,7 +67,7 @@ void testReadInt64() {
     @Test
     void testReadUint32() {
         testRead(() ->
-                rng.nextInt(0, Integer.MAX_VALUE),
+                rng.nextInt(0, MAX_VALUE),
```
Comment (artemananiev) [inline pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java:70]: I like `Integer.MAX_VALUE` more than just `MAX_VALUE`. What if `Integer.MAX_VALUE ` and `Long.MAX_VALUE` are used in the same class? Leaving it up to you, though.

Comment (imalygin) [reply pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoParserToolsTest.java:70]: Yes, qualified name makes sense in this case

File: pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java [hunk 11]
```diff
@@ -0,0 +1,759 @@
...
+        writeOptionalFloat(bufferedData, definition, valToWrite);
+        bufferedData.flip();
+        assertTypeDelimitedTag(definition);
+        assertEquals(MAX_VAR_FLOAT_SIZE, bufferedData.readVarInt(false));
+        assertFixed32Tag(definition.type().optionalFieldDefinition);
+        assertEquals(valToWrite, bufferedData.readFloat(ByteOrder.LITTLE_ENDIAN));
+    }
+
+    @Test
+    void testWriteOptionalFloat_null() {
```
[the remark this answers is not in the document]
Comment (imalygin) [reply pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java:403]: Yes, it does. I added tests.

File: pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java (hunk 6 above)
Comment (imalygin) [reply pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java]: I renamed the constants

File: pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java (hunk 7 above)
Comment (imalygin) [reply pbj-core/pbj-runtime/src/test/java/com/hedera/pbj/runtime/ProtoWriterToolsTest.java]: Yes, it's confusing. Renamed the constant and used a sum of `FLOAT_SIZE` and `TAG_SIZE`

**Review by artemananiev — APPROVED** [review]

File: pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java (hunk 8 above)
Comment (imalygin) [reply pbj-core/pbj-runtime/src/main/java/com/hedera/pbj/runtime/Utf8Tools.java]: Fixed

**Review by artemananiev — APPROVED** [review]
