### PR TITLE
fix: add integ test for write(byte[]) and fix all bugs

### LINKED ISSUE #626: Integration tests for write(byte[])
The recently introduced `write(byte[])` feature should be tested in model integration tests. Any bugs found need to be fixed.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
* Adding integration tests for the new `write(byte[])` feature to check the output against the existing `write(WritableSequentialData)` API
* Fixing all the bugs found along the way

**Related issue(s)**:

Fixes #626

**Notes for reviewer**:
All tests should pass.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java [hunk 1]
```diff
@@ -319,18 +319,47 @@ private static String generateTestMethod(final String modelClassName, final Stri
...
+                                ": in buffer got " + byteBuffer.array()[mismatchIndex] + ", but in array got " + bytesArray[mismatchIndex] +
+                                ".\\nBuffer:\\n" + dataBuffer.toString() +
+                                "\\nArray:\\n" + Arrays.toString(Arrays.copyOf(bytesArray, protoBufByteCount)) +
+                                "\\nModel:\\n" + modelObj +
+                                "\\nProtobuf size:\\n" + protoBufByteCount
+                        );
+                    }
+                    // This check is not precise. An IOOB exception would be best. But we don't want to create new arrays
+                    // for each test so as not to overwhelm the Java GC. So we do this instead:
+                    Arrays.parallelSort(bytesArray, protoBufByteCount, bytesArray.length);
```
Comment (jasperpotts) [inline pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java:352]: I don't understand the sort here. Does write(byte[]) not return number of bytes written?

Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java:352]: It does. However, the return value may be incorrect if there's any bugs in that generated code or in the write methods that can report incorrect bytesWritten if there's any bugs in them.

The sort here ensures that either the tail or the head of the remaining bytes will be non-zero if there's any non-zero bytes written by write(byte[]). This won't protect us from write(byte[]) writing zero bytes though, but this is still a lot faster than allocating a new array with a precise size for each test. I can do the latter, but then the tests will take half an hour+ instead of a couple of minutes.

Comment (anthony-swirldslabs) [reply pbj-core/pbj-compiler/src/main/java/com/hedera/pbj/compiler/impl/generators/TestGenerator.java]: I see what you're saying. The parallelSort wasn't super slow - all tests took under a couple of minutes on my Mac (and about 4 minutes in GitHub: https://github.com/hashgraph/pbj/actions/runs/18016465096/job/51262602372?pr=627 ) which is somewhat comparable with what the tests took before. However, I agree that an O(n log n) sorting should be generally slower than an O(n) iteration. With a simple loop, the tests now take under a minute on my laptop. Not exactly super fast, but better than with sorting. Please see the latest commit.
